### ISSUE TITLE
VariableSpawnerHardness crashes on game load (Version 1.2.1)

### ISSUE THREAD

**Issue by sirben99** [PaintNinja/VariableSpawnerHardness#1]
Hey!

I tried to launch the newest version of VariableSpawnerHardness but it crashed on startup

Minecraft version: 1.16.5
Forge version: 36.0.58
Other mods: No
Client or server: Both
Crash report: 
[crash-2021-03-14_20.36.47-fml.txt](https://github.com/PaintNinja/VariableSpawnerHardness/files/6137331/crash-2021-03-14_20.36.47-fml.txt)
Latest.log:
[latest.log](https://github.com/PaintNinja/VariableSpawnerHardness/files/6137339/latest.log)

Is this something on my end i should update, or is the issues in the mod it self? Since i found this on the report: 
Failure message: Mod File variablespawnerhardness-1.16.5-1.2.1.jar needs language provider javafml:36 or above to load
We have found 35.1
Downgrading to VariableSpawnerHardness 1.2 seems to fix the problem.

I would assume i have to update something but i decidet to inform you here. If it is on my end, please let me know what to do!

Cheers!

**Comment by PaintNinja** [comment]
Thanks for the detailed report, the fix is simple though: While you think you're on Minecraft 1.16.5, the crash report shows that you're still running Minecraft 1.16.4 ;)

Make sure that you installed the mod into the right Forge instance and that Forge actually updated properly first.

**Comment by sirben99** [comment]
> Thanks for the detailed report, the fix is simple though: While you think you're on Minecraft 1.16.5, the crash report shows that you're still running Minecraft 1.16.4 ;)
> 
> Make sure that you installed the mod into the right Forge instance and that Forge actually updated properly first.

Hey!

My bad, this is the wrong crash report, since it dint accually produce one.
I have the latest.log here where the problem shows more cleary:
[latest.log](https://github.com/PaintNinja/VariableSpawnerHardness/files/6137353/latest.log)

Sorry for the inconvinience, but now it should show the proper report!

**Comment by PaintNinja** [comment]
Thanks for the report, the issue has been fixed in https://github.com/PaintNinja/VariableSpawnerHardness/commit/d58596077d44de0ec3db9ac40dca5ef4811536ae and should be available on CurseForge shortly as v1.2.2.
