### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by oliwoli** [PaintNinja/VariableSpawnerHardness#3]
Hello, I couldn't find any LICENSE file for this repo. Could you add it if it's missing? For fabric and forge.
Thank you! :)

**Comment by PaintNinja** [comment]
Whoops! The license is MIT, I'll add that now

**Comment by PaintNinja** [comment]
Done.
Forge: https://github.com/PaintNinja/VariableSpawnerHardness/commit/f6e137155612d486c5d266d6b301698b071bbe44
Fabric: https://github.com/PaintNinja/VariableSpawnerHardness/commit/90c4e02d80e9130858923fa8c64c86bcfe1f31b7
