### ISSUE TITLE
[Forge] 1.18 version is incompatible with 1.18.1

### ISSUE THREAD

**Issue by SimGitHub5** [PaintNinja/VariableSpawnerHardness#6]
Forge-39.0.75 for 1.18.1. Version of the mod is 1.2.2 for 1.18.

When I try to launch Minecraft Forge 1.18.1 with the mod, it says "Mod variablespawnerhardness requires minecraft 1.18. Currently, minecraft is on 1.18.1".

**Comment by PaintNinja** [comment]
Sorry about the delay, somehow missed this. Updated to 1.18.1 and 1.18.2 now.
